In [3]:
import numpy as np
import pandas as pd

In [5]:
filename = 'input2.txt'

In [12]:
df = pd.read_csv(filename, sep=' ', header=None, names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
df

1   2   3   4   5     6     7     8   9  10
0     1   4   5   8  11  12.0   9.0   NaN NaN NaN
1     7   8   9  10  12  15.0  17.0  17.0 NaN NaN
2    17  20  23  25  27  31.0   NaN   NaN NaN NaN
3    55  57  58  61  63  64.0  70.0   NaN NaN NaN
4    39  42  45  43  44   NaN   NaN   NaN NaN NaN
..   ..  ..  ..  ..  ..   ...   ...   ...  ..  ..
995  91  89  87  85  82  81.0  78.0   NaN NaN NaN
996  77  79  81  82  85  86.0   NaN   NaN NaN NaN
997  59  61  62  65  67  68.0   NaN   NaN NaN NaN
998  94  93  92  91  90  87.0  85.0  83.0 NaN NaN
999  50  52  53  54  56  57.0  58.0  61.0 NaN NaN

[1000 rows x 10 columns]

In [16]:
df

1   2   3   4   5     6     7     8
0     1   4   5   8  11  12.0   9.0   NaN
1     7   8   9  10  12  15.0  17.0  17.0
2    17  20  23  25  27  31.0   NaN   NaN
3    55  57  58  61  63  64.0  70.0   NaN
4    39  42  45  43  44   NaN   NaN   NaN
..   ..  ..  ..  ..  ..   ...   ...   ...
995  91  89  87  85  82  81.0  78.0   NaN
996  77  79  81  82  85  86.0   NaN   NaN
997  59  61  62  65  67  68.0   NaN   NaN
998  94  93  92  91  90  87.0  85.0  83.0
999  50  52  53  54  56  57.0  58.0  61.0

[1000 rows x 8 columns]

In [27]:
x = df.to_numpy()
x

array([[ 1.,  4.,  5., ..., 12.,  9., nan],
       [ 7.,  8.,  9., ..., 15., 17., 17.],
       [17., 20., 23., ..., 31., nan, nan],
       ...,
       [59., 61., 62., ..., 68., nan, nan],
       [94., 93., 92., ..., 87., 85., 83.],
       [50., 52., 53., ..., 57., 58., 61.]])

In [20]:
x_diff = np.diff(x)

In [21]:
x_diff

array([[ 3.,  1.,  3., ...,  1., -3., nan],
       [ 1.,  1.,  1., ...,  3.,  2.,  0.],
       [ 3.,  3.,  2., ...,  4., nan, nan],
       ...,
       [ 2.,  1.,  3., ...,  1., nan, nan],
       [-1., -1., -1., ..., -3., -2., -2.],
       [ 2.,  1.,  1., ...,  1.,  1.,  3.]])

In [62]:
safe = []

In [63]:
for row in x_diff:
    #Remove the nan first or all won't work
    row1 = row[~np.isnan(row)]
    
    #Check if all values positive
    if all(i > 0 for i in row1):
        #Check if the values are between 1 and 3
        if all(i >= 1 and i <= 3 for i in row1):
            safe.append(row1)
        else:
            continue
    elif all(i < 0 for i in row1):
        if all(i <= -1 and i >= -3 for i in row1):
            safe.append(row1)

In [70]:
### Editing the above for Part 2 so we can skip the safe rows

In [73]:
safe_ind = []

In [74]:
for index, row in enumerate(x_diff):
    #Remove the nan first or all won't work
    row1 = row[~np.isnan(row)]
    
    #Check if all values positive
    if all(i > 0 for i in row1):
        #Check if the values are between 1 and 3
        if all(i >= 1 and i <= 3 for i in row1):
            safe_ind.append(index)
        else:
            continue
    elif all(i < 0 for i in row1):
        if all(i <= -1 and i >= -3 for i in row1):
            safe_ind.append(index)

In [87]:
x_unsafe = np.delete(x, safe_ind, axis=0)

In [88]:
x.shape

(1000, 8)

In [89]:
x_unsafe.shape

(451, 8)

In [91]:
x_unsafe

array([[ 1.,  4.,  5., ..., 12.,  9., nan],
       [ 7.,  8.,  9., ..., 15., 17., 17.],
       [17., 20., 23., ..., 31., nan, nan],
       ...,
       [85., 87., 86., ..., nan, nan, nan],
       [56., 56., 59., ..., 70., 69., nan],
       [86., 84., 87., ..., 98., 96., nan]])

In [135]:
unsafe_safe = []

In [134]:
a = np.array([23., 20., 18., 17., 14., 11.,  8.,  9.])

In [136]:
#Now we have to be more prescriptive and it in a way where we test if one number is removed from the original array, 
#whether the rules above will hold
for index, row in enumerate(x_unsafe):
    print(index)
    
    #Convert each value to nan in the array in a for loop and remove it 
    for ind, v in enumerate(row):
        print(ind, row)
        row2 = row.copy()
        row2[ind] = np.nan
        print(row2)
        row1 = row2[~np.isnan(row2)] #drop the nan values
        print(row1)
        #Get the difference of the row
        row_diff = np.diff(row1)
        
        if all(i > 0 for i in row_diff) and all(i >= 1 and i <= 3 for i in row_diff):
            print(row_diff)
            #Check if the values are between 1 and 3
            #if all(i >= 1 and i <= 3 for i in row_diff):
            unsafe_safe.append(index)
            print(index, 'True')
            #else:
            #    continue
        elif all(i < 0 for i in row_diff) and all(i <= -1 and i >= -3 for i in row_diff):
            print(row_diff)
            unsafe_safe.append(index)
            print(index, 'True')
        

0
0 [ 1.  4.  5.  8. 11. 12.  9. nan]
[nan  4.  5.  8. 11. 12.  9. nan]
[ 4.  5.  8. 11. 12.  9.]
1 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1. nan  5.  8. 11. 12.  9. nan]
[ 1.  5.  8. 11. 12.  9.]
2 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4. nan  8. 11. 12.  9. nan]
[ 1.  4.  8. 11. 12.  9.]
3 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4.  5. nan 11. 12.  9. nan]
[ 1.  4.  5. 11. 12.  9.]
4 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4.  5.  8. nan 12.  9. nan]
[ 1.  4.  5.  8. 12.  9.]
5 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4.  5.  8. 11. nan  9. nan]
[ 1.  4.  5.  8. 11.  9.]
6 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4.  5.  8. 11. 12. nan nan]
[ 1.  4.  5.  8. 11. 12.]
[3. 1. 3. 3. 1.]
0 True
7 [ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4.  5.  8. 11. 12.  9. nan]
[ 1.  4.  5.  8. 11. 12.  9.]
1
0 [ 7.  8.  9. 10. 12. 15. 17. 17.]
[nan  8.  9. 10. 12. 15. 17. 17.]
[ 8.  9. 10. 12. 15. 17. 17.]
1 [ 7.  8.  9. 10. 12. 15. 17. 17.]
[ 7. nan  9. 10. 12. 15. 17. 17.]
[ 7.  9. 10. 12. 15. 17. 17.]


In [94]:
x_unsafe

array([[ 1.,  4.,  5., ..., 12.,  9., nan],
       [ 7.,  8.,  9., ..., 15., 17., 17.],
       [17., 20., 23., ..., 31., nan, nan],
       ...,
       [85., 87., 86., ..., nan, nan, nan],
       [56., 56., 59., ..., 70., 69., nan],
       [86., 84., 87., ..., 98., 96., nan]])

In [137]:
len(set(unsafe_safe))

40

In [121]:
len(set(unsafe_safe))

19

In [114]:
unsafe_safe

[0,
 1,
 1,
 2,
 3,
 4,
 9,
 9,
 15,
 24,
 24,
 49,
 49,
 74,
 99,
 287,
 287,
 290,
 290,
 316,
 344,
 375,
 392,
 392,
 419,
 428]

In [65]:
len(safe)

549

In [138]:
549+40

589

In [32]:
t = np.array([3.,  1.,  3.,  3.,  1., -3., np.nan])

In [57]:
b = np.array([-1, -3, -2, -1])

In [38]:
all(i >= 1 and i <= 3 for i in t)

False

In [68]:
b[1] = 2

In [69]:
b

array([-1,  2, -2, -1])

In [59]:
all(i <= -1 and i >= -3 for i in b)

True

In [55]:
all(i > 0 for i in b)

False

In [50]:
b[~np.isnan(b)]

array([1., 3., 2., 1.])

In [15]:
df.dropna(axis=1, how='all', inplace=True)

In [2]:
np.loadtxt('input2.txt')

ValueError: the number of columns changed from 7 to 8 at row 2; use `usecols` to select a subset and avoid this error

In [ ]:
with open(filename, 'r') as data:
    